<?php
	define("URL","../../includes/");
	include(URL."configuration.php");
	include(URL."relative_config.php");
	include(URL."classes/mysql.class.php");	
	include(URL."classes/General.class.php");
	include(URL."classes/MenuManager.class.php");
	include(URL."classes/Service.class.php");
?>
